// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Catering.Data;

#nullable disable

namespace ThAmCo.Catering.Migrations
{
    [DbContext(typeof(CateringContext))]
    [Migration("20230106045154_6th jan")]
    partial class _6thjan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodBooking", b =>
                {
                    b.Property<int>("FoodBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodBookingId");

                    b.HasIndex("MenuId");

                    b.ToTable("FoodBookings");

                    b.HasData(
                        new
                        {
                            FoodBookingId = 1,
                            ClientReferenceId = 1,
                            MenuId = 1,
                            NumberOfGuests = 2
                        },
                        new
                        {
                            FoodBookingId = 2,
                            ClientReferenceId = 2,
                            MenuId = 2,
                            NumberOfGuests = 4
                        },
                        new
                        {
                            FoodBookingId = 3,
                            ClientReferenceId = 3,
                            MenuId = 6,
                            NumberOfGuests = 3
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Description = "Delicious Chocolate",
                            UnitPrice = 3.5f
                        },
                        new
                        {
                            FoodItemId = 2,
                            Description = "Steaming Steak",
                            UnitPrice = 5f
                        },
                        new
                        {
                            FoodItemId = 3,
                            Description = "Juicy Burger",
                            UnitPrice = 3.5f
                        },
                        new
                        {
                            FoodItemId = 4,
                            Description = "Mouth watering Fries",
                            UnitPrice = 2.5f
                        },
                        new
                        {
                            FoodItemId = 5,
                            Description = "Fizzy Soda",
                            UnitPrice = 3f
                        },
                        new
                        {
                            FoodItemId = 6,
                            Description = "Hot Tea",
                            UnitPrice = 2.5f
                        },
                        new
                        {
                            FoodItemId = 7,
                            Description = "Warm Coffee",
                            UnitPrice = 2.5f
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "Breakfast"
                        },
                        new
                        {
                            MenuId = 2,
                            MenuName = "Steak & Chips"
                        },
                        new
                        {
                            MenuId = 3,
                            MenuName = "Burger & Fries"
                        },
                        new
                        {
                            MenuId = 4,
                            MenuName = "Steak"
                        },
                        new
                        {
                            MenuId = 5,
                            MenuName = "Burger"
                        },
                        new
                        {
                            MenuId = 6,
                            MenuName = "Fries"
                        },
                        new
                        {
                            MenuId = 7,
                            MenuName = "Burger & Tea"
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodItemId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuFoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            MenuId = 1
                        },
                        new
                        {
                            FoodItemId = 2,
                            MenuId = 2
                        },
                        new
                        {
                            FoodItemId = 3,
                            MenuId = 3
                        },
                        new
                        {
                            FoodItemId = 4,
                            MenuId = 4
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodBooking", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.Menu", "Menu")
                        .WithMany("FoodBookings")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.FoodItem", "FoodItem")
                        .WithMany("Menus")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.Data.Menu", "Menu")
                        .WithMany("FoodItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodItem", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.Navigation("FoodBookings");

                    b.Navigation("FoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
